name: check
env:
  TZ: "Asia/Tokyo"


on:
  push:
    branches:
      - "main"

jobs:
  check_branch:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Update npm
        run: npm install -g npm
      - name: install packages
        run: npm ci
      - name: check
        run: npm run build
